[
  ["spi.miso_gpio", "i", -1, {title: "GPIO to use for MISO"}],
  ["spi.mosi_gpio", "i", -1, {title: "GPIO to use for MOSI"}],
  ["spi.sclk_gpio", "i", -1, {title: "GPIO to use for SCLK"}],
  ["spi.cs0_gpio", "i", -1, {title: "GPIO to use for CS0"}],
  ["spi.cs1_gpio", "i", -1, {title: "GPIO to use for CS1"}],
  ["spi.cs2_gpio", "i", -1, {title: "GPIO to use for CS2"}],
]
